### ISSUE TITLE
Expresiones Booleanas

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/actividad-10-expresiones-boolenas-team-sael-1as#1]
[(EXPRESIONES BOOLEANAS)..pdf](https://github.com/user-attachments/files/18044436/EXPRESIONES.BOOLEANAS.pdf)

**Comment by Victor-noe12** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
